"""initial model

Revision ID: f1c23c3cf448
Revises: 
Create Date: 2023-11-28 11:32:15.713490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1c23c3cf448'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyer',
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('slug'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug'),
    schema='public'
    )
    op.create_table('make',
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('slug'),
    sa.UniqueConstraint('name'),
    schema='public'
    )
    op.create_table('year',
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('slug'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug'),
    schema='public'
    )
    op.create_table('buyer_dealer',
    sa.Column('buyer_slug', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('zipcode', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['buyer_slug'], ['public.buyer.slug'], ),
    sa.PrimaryKeyConstraint('buyer_slug', 'code'),
    schema='public'
    )
    op.create_table('buyer_make',
    sa.Column('buyer_slug', sa.String(length=50), nullable=False),
    sa.Column('make_slug', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['buyer_slug'], ['public.buyer.slug'], ),
    sa.ForeignKeyConstraint(['make_slug'], ['public.make.slug'], ),
    sa.PrimaryKeyConstraint('buyer_slug', 'make_slug'),
    schema='public'
    )
    op.create_table('buyer_tier',
    sa.Column('buyer_slug', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['buyer_slug'], ['public.buyer.slug'], ),
    sa.PrimaryKeyConstraint('buyer_slug', 'slug'),
    sa.UniqueConstraint('buyer_slug', 'name'),
    schema='public'
    )
    op.create_table('make_model',
    sa.Column('make_slug', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['make_slug'], ['public.make.slug'], ),
    sa.PrimaryKeyConstraint('make_slug', 'slug'),
    sa.UniqueConstraint('make_slug', 'name'),
    schema='public'
    )
    op.create_table('make_year',
    sa.Column('make_slug', sa.String(length=50), nullable=False),
    sa.Column('year_slug', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['make_slug'], ['public.make.slug'], ),
    sa.ForeignKeyConstraint(['year_slug'], ['public.year.slug'], ),
    sa.PrimaryKeyConstraint('make_slug', 'year_slug'),
    schema='public'
    )
    op.create_table('buyer_dealer_coverage',
    sa.Column('buyer_slug', sa.String(length=50), nullable=False),
    sa.Column('buyer_dealer_code', sa.String(length=50), nullable=False),
    sa.Column('zipcode', sa.String(length=255), nullable=False),
    sa.Column('distance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_slug', 'buyer_dealer_code'], ['public.buyer_dealer.buyer_slug', 'public.buyer_dealer.code'], ),
    sa.PrimaryKeyConstraint('buyer_slug', 'buyer_dealer_code', 'zipcode'),
    schema='public'
    )
    op.create_table('buyer_dealer_make',
    sa.Column('buyer_slug', sa.String(length=50), nullable=False),
    sa.Column('buyer_dealer_code', sa.String(length=15), nullable=False),
    sa.Column('make_slug', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['buyer_slug', 'buyer_dealer_code'], ['public.buyer_dealer.buyer_slug', 'public.buyer_dealer.code'], ),
    sa.ForeignKeyConstraint(['buyer_slug', 'make_slug'], ['public.buyer_make.buyer_slug', 'public.buyer_make.make_slug'], ),
    sa.PrimaryKeyConstraint('buyer_slug', 'buyer_dealer_code', 'make_slug'),
    schema='public'
    )
    op.create_table('buyer_make_year',
    sa.Column('buyer_slug', sa.String(length=50), nullable=False),
    sa.Column('make_slug', sa.String(length=50), nullable=False),
    sa.Column('year_slug', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['buyer_slug', 'make_slug'], ['public.buyer_make.buyer_slug', 'public.buyer_make.make_slug'], ),
    sa.ForeignKeyConstraint(['make_slug', 'year_slug'], ['public.make_year.make_slug', 'public.make_year.year_slug'], ),
    sa.PrimaryKeyConstraint('buyer_slug', 'make_slug', 'year_slug'),
    schema='public'
    )
    op.create_table('buyer_tier_make',
    sa.Column('buyer_slug', sa.String(length=50), nullable=False),
    sa.Column('tier_slug', sa.String(length=50), nullable=False),
    sa.Column('make_slug', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['buyer_slug', 'make_slug'], ['public.buyer_make.buyer_slug', 'public.buyer_make.make_slug'], ),
    sa.ForeignKeyConstraint(['buyer_slug', 'tier_slug'], ['public.buyer_tier.buyer_slug', 'public.buyer_tier.slug'], ),
    sa.PrimaryKeyConstraint('buyer_slug', 'tier_slug', 'make_slug'),
    schema='public'
    )
    op.create_table('legacy_buyer_tier',
    sa.Column('buyer_slug', sa.String(length=50), nullable=False),
    sa.Column('buyer_tier_slug', sa.String(length=50), nullable=False),
    sa.Column('legacy_id', sa.Integer(), nullable=False),
    sa.Column('legacy_name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['buyer_slug', 'buyer_tier_slug'], ['public.buyer_tier.buyer_slug', 'public.buyer_tier.slug'], ),
    sa.PrimaryKeyConstraint('buyer_slug', 'buyer_tier_slug'),
    sa.UniqueConstraint('legacy_id'),
    sa.UniqueConstraint('legacy_name'),
    schema='public'
    )
    op.create_table('make_model_year',
    sa.Column('make_slug', sa.String(length=50), nullable=False),
    sa.Column('model_slug', sa.String(length=50), nullable=False),
    sa.Column('year_slug', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['make_slug', 'model_slug'], ['public.make_model.make_slug', 'public.make_model.slug'], ),
    sa.ForeignKeyConstraint(['make_slug', 'year_slug'], ['public.make_year.make_slug', 'public.make_year.year_slug'], ),
    sa.PrimaryKeyConstraint('make_slug', 'model_slug', 'year_slug'),
    schema='public'
    )
    op.create_table('buyer_tier_make_year',
    sa.Column('buyer_slug', sa.String(length=50), nullable=False),
    sa.Column('tier_slug', sa.String(length=50), nullable=False),
    sa.Column('make_slug', sa.String(length=50), nullable=False),
    sa.Column('year_slug', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['buyer_slug', 'make_slug', 'year_slug'], ['public.buyer_make_year.buyer_slug', 'public.buyer_make_year.make_slug', 'public.buyer_make_year.year_slug'], ),
    sa.ForeignKeyConstraint(['buyer_slug', 'tier_slug', 'make_slug'], ['public.buyer_tier_make.buyer_slug', 'public.buyer_tier_make.tier_slug', 'public.buyer_tier_make.make_slug'], ),
    sa.PrimaryKeyConstraint('buyer_slug', 'tier_slug', 'make_slug', 'year_slug'),
    schema='public'
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buyer_tier_make_year', schema='public')
    op.drop_table('make_model_year', schema='public')
    op.drop_table('legacy_buyer_tier', schema='public')
    op.drop_table('buyer_tier_make', schema='public')
    op.drop_table('buyer_make_year', schema='public')
    op.drop_table('buyer_dealer_make', schema='public')
    op.drop_table('buyer_dealer_coverage', schema='public')
    op.drop_table('make_year', schema='public')
    op.drop_table('make_model', schema='public')
    op.drop_table('buyer_tier', schema='public')
    op.drop_table('buyer_make', schema='public')
    op.drop_table('buyer_dealer', schema='public')
    op.drop_table('year', schema='public')
    op.drop_table('make', schema='public')
    op.drop_table('buyer', schema='public')
    # ### end Alembic commands ###
